version: '3'
services:
  web:
    container_name: crux_forum_website
    ports:
      - '3000:3000'
    build:
      dockerfile: Dockerfile
      context: ./
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
